live_view_studio/lib/live_view_studio_web/router.ex
defmodule LiveViewStudioWeb.Router do
  use LiveViewStudioWeb, :router

  import LiveViewStudioWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LiveViewStudioWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LiveViewStudioWeb do
    pipe_through :browser

    live "/", PageLive
    live "/light", LightLive
    live "/license", LicenseLive
    live "/sales-dashboard", SalesDashboardLive
    live "/search", SearchLive
    live "/autocomplete", AutocompleteLive
    live "/flights", FlightsLiveLive
    live "/filter", FilterLive
    live "/git-repos", GitReposLive
    live "/servers", ServersLive
    live "/paginate", PaginateLive
    live "/vehicles", VehiclesLive
    live "/sort", SortLive
  end

  # Other scopes may use custom stacks.
  # scope "/api", LiveViewStudioWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LiveViewStudioWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", LiveViewStudioWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", LiveViewStudioWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", LiveViewStudioWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

live_view_studio/lib/live_view_studio_web/controllers/page_controller.ex
defmodule LiveViewStudioWeb.PageController do
  use LiveViewStudioWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

live_view_studio/lib/live_view_studio_web/controllers/user_confirmation_controller.ex
defmodule LiveViewStudioWeb.UserConfirmationController do
  use LiveViewStudioWeb, :controller

  alias LiveViewStudio.Accounts

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email}}) do
    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_confirmation_instructions(
        user,
        &Routes.user_confirmation_url(conn, :edit, &1)
      )
    end

    # In order to prevent user enumeration attacks, regardless of the outcome, show an impartial success/error message.
    conn
    |> put_flash(
      :info,
      "If your email is in our system and it has not been confirmed yet, " <>
        "you will receive an email with instructions shortly."
    )
    |> redirect(to: "/")
  end

  def edit(conn, %{"token" => token}) do
    render(conn, "edit.html", token: token)
  end

  # Do not log in the user after confirmation to avoid a
  # leaked token giving the user access to the account.
  def update(conn, %{"token" => token}) do
    case Accounts.confirm_user(token) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "User confirmed successfully.")
        |> redirect(to: "/")

      :error ->
        # If there is a current user and the account was already confirmed,
        # then odds are that the confirmation link was already visited, either
        # by some automation or by the user themselves, so we redirect without
        # a warning message.
        case conn.assigns do
          %{current_user: %{confirmed_at: confirmed_at}} when not is_nil(confirmed_at) ->
            redirect(conn, to: "/")

          %{} ->
            conn
            |> put_flash(:error, "User confirmation link is invalid or it has expired.")
            |> redirect(to: "/")
        end
    end
  end
end

live_view_studio/lib/live_view_studio_web/controllers/user_registration_controller.ex
defmodule LiveViewStudioWeb.UserRegistrationController do
  use LiveViewStudioWeb, :controller

  alias LiveViewStudio.Accounts
  alias LiveViewStudio.Accounts.User
  alias LiveViewStudioWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

live_view_studio/lib/live_view_studio_web/controllers/user_reset_password_controller.ex
defmodule LiveViewStudioWeb.UserResetPasswordController do
  use LiveViewStudioWeb, :controller

  alias LiveViewStudio.Accounts

  plug :get_user_by_reset_password_token when action in [:edit, :update]

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email}}) do
    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_reset_password_instructions(
        user,
        &Routes.user_reset_password_url(conn, :edit, &1)
      )
    end

    # In order to prevent user enumeration attacks, regardless of the outcome, show an impartial success/error message.
    conn
    |> put_flash(
      :info,
      "If your email is in our system, you will receive instructions to reset your password shortly."
    )
    |> redirect(to: "/")
  end

  def edit(conn, _params) do
    render(conn, "edit.html", changeset: Accounts.change_user_password(conn.assigns.user))
  end

  # Do not log in the user after reset password to avoid a
  # leaked token giving the user access to the account.
  def update(conn, %{"user" => user_params}) do
    case Accounts.reset_user_password(conn.assigns.user, user_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Password reset successfully.")
        |> redirect(to: Routes.user_session_path(conn, :new))

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  defp get_user_by_reset_password_token(conn, _opts) do
    %{"token" => token} = conn.params

    if user = Accounts.get_user_by_reset_password_token(token) do
      conn |> assign(:user, user) |> assign(:token, token)
    else
      conn
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: "/")
      |> halt()
    end
  end
end

live_view_studio/lib/live_view_studio_web/controllers/user_session_controller.ex
defmodule LiveViewStudioWeb.UserSessionController do
  use LiveViewStudioWeb, :controller

  alias LiveViewStudio.Accounts
  alias LiveViewStudioWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

live_view_studio/lib/live_view_studio_web/controllers/user_settings_controller.ex
defmodule LiveViewStudioWeb.UserSettingsController do
  use LiveViewStudioWeb, :controller

  alias LiveViewStudio.Accounts
  alias LiveViewStudioWeb.UserAuth

  plug :assign_email_and_password_changesets

  def edit(conn, _params) do
    render(conn, "edit.html")
  end

  def update(conn, %{"action" => "update_email"} = params) do
    %{"current_password" => password, "user" => user_params} = params
    user = conn.assigns.current_user

    case Accounts.apply_user_email(user, password, user_params) do
      {:ok, applied_user} ->
        Accounts.deliver_update_email_instructions(
          applied_user,
          user.email,
          &Routes.user_settings_url(conn, :confirm_email, &1)
        )

        conn
        |> put_flash(
          :info,
          "A link to confirm your email change has been sent to the new address."
        )
        |> redirect(to: Routes.user_settings_path(conn, :edit))

      {:error, changeset} ->
        render(conn, "edit.html", email_changeset: changeset)
    end
  end

  def update(conn, %{"action" => "update_password"} = params) do
    %{"current_password" => password, "user" => user_params} = params
    user = conn.assigns.current_user

    case Accounts.update_user_password(user, password, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Password updated successfully.")
        |> put_session(:user_return_to, Routes.user_settings_path(conn, :edit))
        |> UserAuth.log_in_user(user)

      {:error, changeset} ->
        render(conn, "edit.html", password_changeset: changeset)
    end
  end

  def confirm_email(conn, %{"token" => token}) do
    case Accounts.update_user_email(conn.assigns.current_user, token) do
      :ok ->
        conn
        |> put_flash(:info, "Email changed successfully.")
        |> redirect(to: Routes.user_settings_path(conn, :edit))

      :error ->
        conn
        |> put_flash(:error, "Email change link is invalid or it has expired.")
        |> redirect(to: Routes.user_settings_path(conn, :edit))
    end
  end

  defp assign_email_and_password_changesets(conn, _opts) do
    user = conn.assigns.current_user

    conn
    |> assign(:email_changeset, Accounts.change_user_email(user))
    |> assign(:password_changeset, Accounts.change_user_password(user))
  end
end

live_view_studio/lib/live_view_studio_web/live/autocomplete_live.ex
defmodule LiveViewStudioWeb.AutocompleteLive do
  use LiveViewStudioWeb, :live_view

  alias LiveViewStudio.{Cities, Stores}

  def mount(_params, _session, socket) do
    socket =
      assign(socket,
        zip: "",
        city: "",
        stores: [],
        matches: [],
        loading: false
      )

    {:ok, socket, temporary_assigns: [stores: [], matches: []]}
  end

  def render(assigns) do
    ~H"""
    <h1>Find a Store</h1>
    <div id="search">

      <form phx-submit="zip-search">
        <input type="text" name="zip" value={@zip}
               placeholder="Zip Code"
               autofocus autocomplete="off"
               readonly={@loading} />

        <button type="submit">
          <img src="images/search.svg">
        </button>
      </form>

      <form phx-submit="city-search" phx-change="suggest-city">
        <input type="text" name="city" value={@city}
               placeholder="City"
               autocomplete="off"
               list="matches"
               phx-debounce="1000"
               readonly={@loading} />

        <button type="submit">
          <img src="images/search.svg">
        </button>
      </form>

      <datalist id="matches">
        <%= for match <- @matches do %>
          <option value={match}><%= match %></option>
        <% end %>
      </datalist>


      <%= if @loading do %>
        <div class="loader">
          Loading...
        </div>
      <% end %>

      <div class="stores">
        <ul>
          <%= for store <- @stores do %>
            <li>
              <div class="first-line">
                <div class="name">
                  <%= store.name %>
                </div>
                <div class="status">
                  <%= if store.open do %>
                    <span class="open">Open</span>
                  <% else %>
                    <span class="closed">Closed</span>
                  <% end %>
                </div>
              </div>
              <div class="second-line">
                <div class="street">
                  <img src="images/location.svg">
                  <%= store.street %>
                </div>
                <div class="phone_number">
                  <img src="images/phone.svg">
                  <%= store.phone_number %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    """
  end

  def handle_event("zip-search", %{"zip" => zip}, socket) do
    Process.send_after(self(), {:zip_search, zip}, 500)

    socket =
      assign(socket,
        zip: zip,
        stores: [],
        loading: true
      )

    {:noreply, socket}
  end

  def handle_event("suggest-city", %{"city" => prefix}, socket) do
    socket = assign(socket, matches: Cities.suggest(prefix))
    {:noreply, socket}
  end

  def handle_event("city-search", %{"city" => city}, socket) do
    Process.send_after(self(), {:city_search, city}, 500)

    socket =
      assign(socket,
        city: city,
        stores: [],
        loading: true
      )

    {:noreply, socket}
  end

  def handle_info({:zip_search, zip}, socket) do
    socket =
      case Stores.search_by_zip(zip) do
        [] ->
          socket
          |> put_flash(:info, ~s(No stores matching "#{zip}"))
          |> assign(stores: [], loading: false)

        stores ->
          socket
          |> assign(stores: stores, loading: false)
      end

    {:noreply, socket}
  end

  def handle_info({:city_search, city}, socket) do
    socket =
      case Stores.search_by_city(city) do
        [] ->
          socket
          |> put_flash(:info, ~s(No stores matching "#{city}"))
          |> assign(stores: [], loading: false)

        stores ->
          socket
          |> assign(stores: stores, loading: false)
      end

    {:noreply, socket}
  end
end

live_view_studio/lib/live_view_studio_web/live/license_live.ex
defmodule LiveViewStudioWeb.LicenseLive do
  use LiveViewStudioWeb, :live_view

  alias LiveViewStudio.Licenses
  import Number.Currency

  def mount(_params, _session, socket) do
    if connected?(socket) do
      :timer.send_interval(1000, self(), :tick)
    end

    expiration_time = Timex.shift(Timex.now(), hours: 1)

    socket =
      assign(socket,
        seats: 2,
        amount: Licenses.calculate(2),
        expiration_time: expiration_time,
        time_remaining: time_remaining(expiration_time)
      )

    {:ok, socket}
  end

  def render(assigns) do
    ~H"""
    <h1>Team License</h1>
    <div id="license">
      <div class="card">
        <div class="content">
          <p class="m-4 font-semibold text-indigo-800">
            <%= if @time_remaining > 0 do %>
              <%= format_time(@time_remaining) %> left to save 20%
            <% else %>
              Expired!
            <% end %>
          </p>
          <div class="seats">
            <img src="images/license.svg">
            <span>
              Your license is currently for
              <strong><%= @seats %></strong> <%= ngettext("seat", "seats", @seats) %>.
            </span>
          </div>
          <form phx-change="update">
            <input type="range"
                  min="1"
                  max="10"
                  name="seats"
                  phx-debounce="250"
                  value={@seats} />
          </form>
          <div class="amount">
            <%= number_to_currency(@amount) %>
          </div>
        </div>
      </div>
    </div>
    """
  end

  def handle_event("update", %{"seats" => seats}, socket) do
    seats = String.to_integer(seats)
    socket = assign(socket, seats: seats, amount: Licenses.calculate(seats))
    {:noreply, socket}
  end

  def handle_info(:tick, socket) do
    expiration_time = socket.assigns.expiration_time
    socket = assign(socket, time_remaining: time_remaining(expiration_time))
    {:noreply, socket}
  end

  defp time_remaining(expiration_time) do
    DateTime.diff(expiration_time, Timex.now())
  end

  defp format_time(time) do
    time
    |> Timex.Duration.from_seconds()
    |> Timex.format_duration(:humanized)
  end
end

live_view_studio/lib/live_view_studio_web/live/page_live.html.heex
<h1 class="bg-clip-text text-transparent bg-gradient-to-r from-orange-400 to-red-500 mb-2">
  🔥 Phoenix LiveView Course Demos 🔥
</h1>

<div class="text-center mt-6 mb-12">
  <button class="bg-orange-500 text-white font-bold py-2 px-4 rounded outline-none hover:bg-orange-600 active:bg-orange-500 text-lg">
      <a target="_blank" href="https://agile-equatorial-stoat.gigalixirapp.com">LiveView Course Demos</a>
  </button>
  <button class="bg-orange-500 text-white font-bold py-2 px-4 rounded outline-none hover:bg-orange-600 active:bg-orange-500 text-lg">
    <a target="_blank" href="https://pragmaticstudio.com/phoenix-liveview">Get The Course!</a>
  </button>
</div>

<ul class="examples">
  <li>
    <%= live_redirect "Button Clicks", to: Routes.live_path(@socket, LiveViewStudioWeb.LightLive) %>
  </li>
  <li>
    <%= live_redirect "Dynamic Form", to: Routes.live_path(@socket, LiveViewStudioWeb.LicenseLive) %>
  </li>
  <li>
    <%= live_redirect "Dashboard", to: Routes.live_path(@socket, LiveViewStudioWeb.SalesDashboardLive) %>
  </li>
  <li>
    <%= live_redirect "Live Search", to: Routes.live_path(@socket, LiveViewStudioWeb.SearchLive) %>
  </li>
  <li>
    <%= live_redirect "Autocomplete", to: Routes.live_path(@socket, LiveViewStudioWeb.AutocompleteLive) %>
  </li>
  <li>
    <%= live_redirect "Flight Search", to: Routes.live_path(@socket, LiveViewStudioWeb.FlightsLiveLive) %>
  </li>
  <li>
    <%= live_redirect "Filtering", to: Routes.live_path(@socket, LiveViewStudioWeb.FilterLive) %>
  </li>
  <li>
    <%= live_redirect "Git Repositories", to: Routes.live_path(@socket, LiveViewStudioWeb.GitReposLive) %>
  </li>
  <li>
    <%= live_redirect "Servers", to: Routes.live_path(@socket, LiveViewStudioWeb.ServersLive) %>
  </li>
  <li>
    <%= live_redirect "Paginate", to: Routes.live_path(@socket, LiveViewStudioWeb.PaginateLive) %>
  </li>
  <li>
    <%= live_redirect "Vehicles", to: Routes.live_path(@socket, LiveViewStudioWeb.VehiclesLive) %>
  </li>
  <li>
    <%= live_redirect "Sort", to: Routes.live_path(@socket, LiveViewStudioWeb.SortLive) %>
  </li>
</ul>

live_view_studio/lib/live_view_studio_web/live/paginate_live.html.heex
<h1>Food Bank Donations</h1>
<div id="donations">
  <form phx-change="select-per-page">
    Show
    <select name="per-page">
      <%= options_for_select([5, 10, 15, 20], @options.per_page) %>
    </select>
    <label for="per-page">per page</label>
  </form>
  <div class="wrapper">
    <table>
      <thead>
        <tr>
          <th class="item">
            Item
          </th>
          <th>
            Quantity
          </th>
          <th>
            Days Until Expires
          </th>
        </tr>
      </thead>
      <tbody>
        <%= for donation <- @donations do %>
          <tr>
            <td class="item">
              <span class="id"><%= donation.id %></span>
              <%= donation.emoji %> <%= donation.item %>
            </td>
            <td>
              <%= donation.quantity %> lbs
            </td>
            <td>
              <span class={expires_class(donation)}>
                <%= donation.days_until_expires %>
              </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="footer">
      <div class="pagination">
        <%= if @options.page > 1 do %>
          <%= pagination_link(@socket,
                              "Previous",
                              @options.page - 1,
                              @options.per_page,
                              "previous") %>
        <% end %>
        <%= for i <- (@options.page - 2)..(@options.page + 2), i > 0 do %>
          <%= pagination_link(@socket,
                              i,
                              i,
                              @options.per_page,
                              (if i == @options.page, do: "active")) %>
        <% end %>
        <%= pagination_link(@socket,
                              "Next",
                              @options.page + 1,
                              @options.per_page,
                              "next") %>
      </div>
    </div>
  </div>
</div>

live_view_studio/lib/live_view_studio_web/live/sort_live.html.heex
<h1>Food Bank Donations</h1>
<div id="donations">
  <form phx-change="select-per-page">
    Show
    <select name="per-page">
      <%= options_for_select([5, 10, 15, 20], @options.per_page) %>
    </select>
    <label for="per-page">per page</label>
  </form>
  <div class="wrapper">
    <table>
      <thead>
        <tr>
          <th class="item">
            <%= sort_link(@socket, "Item", :item, @options) %>
          </th>
          <th>
            <%= sort_link(@socket, "Quantity", :quantity, @options) %>
          </th>
          <th>
            <%= sort_link(@socket, "Days Until Expires", :days_until_expires, @options) %>
          </th>
        </tr>
      </thead>
      <tbody>
        <%= for donation <- @donations do %>
          <tr>
            <td class="item">
              <span class="id"><%= donation.id %></span>
              <%= donation.emoji %> <%= donation.item %>
            </td>
            <td>
              <%= donation.quantity %> lbs
            </td>
            <td>
              <span class={expires_class(donation)}>
                <%= donation.days_until_expires %>
              </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="footer">
      <div class="pagination">
        <%= if @options.page > 1 do %>
          <%= pagination_link(@socket,
                              "Previous",
                              @options.page - 1,
                              @options,
                              "previous") %>
        <% end %>
        <%= for i <- (@options.page - 2)..(@options.page + 2), i > 0 do %>
          <%= if i <= ceil(@total_donations / @options.per_page) do %>
            <%= pagination_link(@socket,
                                i,
                                i,
                                @options,
                                (if i == @options.page, do: "active")) %>
          <% end %>
        <% end %>
        <%= if (@options.page * @options.per_page) < @total_donations do %>
          <%= pagination_link(@socket,
                                "Next",
                                @options.page + 1,
                                @options,
                                "next") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

live_view_studio/lib/live_view_studio_web/live/vehicles_live.html.heex
<h1>🚙 Vehicles 🚘</h1>
<div id="vehicles">
  <form phx-change="select-per-page">
    Show
    <select name="per-page">
      <%= options_for_select([5, 10, 15, 20], @options.per_page) %>
    </select>
    <label for="per-page">per page</label>
  </form>
  <div class="wrapper">
    <table>
      <thead>
        <tr>
          <th>
            ID
          </th>
          <th>
            Make
          </th>
          <th>
            Model
          </th>
          <th>
            Color
          </th>
        </tr>
      </thead>
      <tbody>
        <%= for vehicle <- @vehicles do %>
          <tr>
            <td>
              <%= vehicle.id %>
            </td>
            <td>
              <%= vehicle.make %>
            </td>
            <td>
              <%= vehicle.model %>
            </td>
            <td>
              <%= vehicle.color %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="footer">
      <div class="pagination">
        <%= if @options.page > 1 do %>
          <%= pagination_link(@socket,
                              "Previous",
                              @options.page - 1,
                              @options.per_page,
                              "previous") %>
        <% end %>
        <%= for i <- (@options.page - 2)..(@options.page + 2), i > 0 do %>
          <%= if i <= ceil(@total_vehicles / @options.per_page) do %>
            <%= pagination_link(@socket,
                                i,
                                i,
                                @options.per_page,
                                (if i == @options.page, do: "active")) %>
          <% end %>
        <% end %>
        <%= if (@options.page * @options.per_page) < @total_vehicles do %>
          <%= pagination_link(@socket,
                                "Next",
                                @options.page + 1,
                                @options.per_page,
                                "next") %>
        <% end %>
      </div>
    </div>
  </div>
</div>